version: '3'
services:
  redis:
    container_name: redis-thinkpay
    image: "redis:alpine"
    ports:
      - "6380:6379"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../redis:/data
    restart: unless-stopped
    expose:
      - 6380
    environment:
      - 'API_PORT=6379'
